# Workflow for CI debug build
name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '.git**'
  pull_request:
    branches:
      - main
      - example/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Spice
        uses: spicelang/spice-setup-action@v1

      - name: Test examples
        run: spice run ./.github/scripts/test-examples.spice